import { readFileSync } from 'node:fs'
import { execa } from 'execa'
import { assertSafeToFormat, withFormatLock } from './storage-safety.js'
import { exec, sudoWrap, writeFileAsRoot } from '../lib/exec.js'

/**
 * Atomically write content to a root-owned path via sudo.
 * The backend runs as 'homenas' (non-root) so plain writeFileSync to /etc/*
 * fails with EACCES. We stage in /tmp, then `install` it with root ownership.
 */
async function writeRootFile(target: string, content: string, mode: string = '0644'): Promise<void> {
  await writeFileAsRoot(target, content, parseInt(mode, 8))
}

export type DiskRole = 'data' | 'parity' | 'cache'
export type PoolType = 'single' | 'mergerfs' | 'snapraid'
export type FsType = 'ext4' | 'xfs'

export interface DiskConfig {
  device: string   // e.g. /dev/sda
  role: DiskRole
}

export interface PoolConfig {
  disks: DiskConfig[]
  fsType: FsType
  poolType: PoolType
}

// ── Input validation ──────────────────────────────────────────────────────────

const DEVICE_RE = /^\/dev\/(sd[a-z]+|hd[a-z]+|nvme\d+n\d+|mmcblk\d+|vd[a-z]+)$/

function validateDevice(device: string): void {
  if (!DEVICE_RE.test(device)) throw new Error(`Invalid device path: ${device}`)
}

// Partition suffix: /dev/sda → /dev/sda1, /dev/nvme0n1 → /dev/nvme0n1p1
function partitionDevice(device: string): string {
  if (/nvme|mmcblk/.test(device)) return device + 'p1'
  return device + '1'
}

// ── Prepare disk (unmount + wipe) ─────────────────────────────────────────────

async function prepDisk(device: string): Promise<void> {
  // Mounted disks and RAID/LVM holders were rejected by preflight. Never
  // deactivate unrelated volume groups or lazily detach filesystems here.
  for (const [command, args] of [
    ['wipefs', ['-a', '-f', device]],
    ['dd', ['if=/dev/zero', `of=${device}`, 'bs=1M', 'count=10', 'conv=fsync']],
    ['partprobe', [device]],
  ] as [string, string[]][]) {
    const result = await exec(command, args)
    if (result.exitCode !== 0) throw new Error(`${command} failed on ${device}: ${result.stderr}`)
  }
}

// ── Format a single disk ──────────────────────────────────────────────────────

async function formatDisk(device: string, fsType: FsType, role: DiskRole): Promise<void> {
  // Unmount and wipe any existing data before touching the partition table
  await prepDisk(device)

  // Create GPT partition table
  const labelResult = await execa(...sudoWrap('parted', ['-s', device, 'mklabel', 'gpt']), { shell: false, reject: false })
  if (labelResult.exitCode !== 0) {
    throw new Error(`Failed to create GPT on ${device}: ${labelResult.stderr}`)
  }

  // Create single partition
  const mkPartResult = await execa(...sudoWrap('parted', ['-s', device, 'mkpart', 'primary', fsType, '0%', '100%']), { shell: false, reject: false })
  if (mkPartResult.exitCode !== 0) {
    throw new Error(`Failed to create partition on ${device}: ${mkPartResult.stderr}`)
  }

  // Re-read partition table and wait for udev to create the partition device node
  await execa(...sudoWrap('partprobe', [device]), { shell: false, reject: false })
  await execa(...sudoWrap('udevadm', ['settle', '--timeout=10']), { shell: false, reject: false })

  const partition = partitionDevice(device)
  const label = `${role}_${device.replace('/dev/', '')}`.substring(0, 16)

  // Wait up to 10 s for the partition node to appear (udevadm settle not always enough)
  const deadline = Date.now() + 10_000
  while (!await execa(...sudoWrap('test', ['-b', partition]), { shell: false, reject: false }).then(r => r.exitCode === 0)) {
    if (Date.now() > deadline) throw new Error(`Partition device ${partition} did not appear after 10s`)
    await new Promise<void>(r => setTimeout(r, 500))
  }

  // Format — use absolute paths because the service may not have /sbin in PATH
  let fmtResult
  if (fsType === 'xfs') {
    fmtResult = await execa(...sudoWrap('/sbin/mkfs.xfs', ['-f', '-L', label, partition]), { shell: false, reject: false })
  } else {
    fmtResult = await execa(...sudoWrap('/sbin/mkfs.ext4', ['-F', '-L', label, partition]), { shell: false, reject: false })
  }

  if (fmtResult.exitCode !== 0) {
    throw new Error(`Failed to format ${partition}: ${fmtResult.stderr || fmtResult.stdout}`)
  }
}

// ── SnapRAID configuration ────────────────────────────────────────────────────

async function writeSnapraidConf(dataMounts: string[], parityMounts: string[]): Promise<void> {
  const SECOND_PARITY = ['second', 'third', 'fourth', 'fifth', 'sixth']

  let conf = '# SnapRAID configuration — generated by HomeNas OS v3\n\n'

  parityMounts.forEach((m, i) => {
    const label = i === 0 ? 'parity' : `${SECOND_PARITY[i - 1] ?? i + 1 + 'th'}-parity`
    conf += `${label} ${m}/snapraid.parity\n`
  })
  conf += '\n'

  dataMounts.forEach(m => { conf += `content ${m}/.snapraid/snapraid.content\n` })
  if (parityMounts.length) conf += `content ${parityMounts[0]}/.snapraid/snapraid.content\n`
  conf += '\n'

  dataMounts.forEach((m, i) => { conf += `disk d${i + 1} ${m}\n` })
  conf += '\n'

  conf += 'exclude *.unrecoverable\nexclude /tmp/\nexclude /lost+found/\nexclude /.snapraid/\n'

  // /etc/snapraid.conf is root-owned (same EACCES path as /etc/fstab).
  await writeRootFile('/etc/snapraid.conf', conf)
}

// ── MergerFS pool ─────────────────────────────────────────────────────────────

async function mountMergerFS(cacheMounts: string[], dataMounts: string[]): Promise<void> {
  const POOL = '/mnt/storage'
  // /mnt/storage is root-owned — must mkdir via sudo (see same fix applied to disk mountpoints).
  const mkdirPool = await execa(...sudoWrap('mkdir', ['-p', POOL]), { shell: false, reject: false })
  if (mkdirPool.exitCode !== 0) throw new Error(`Failed to create pool mount point ${POOL}: ${mkdirPool.stderr}`)

  // Cache disks FIRST so the ff (first found) policy always writes there.
  // Data disks follow as overflow once the cache is full.
  const sources = [...cacheMounts, ...dataMounts].join(':')

  // func.create=ff: new files go to the first branch with enough space (cache).
  // moveonenospc: if cache fills up, spill to next branch automatically.
  const r = await execa(
    ...sudoWrap('mergerfs', [sources, POOL, '-o', 'defaults,allow_other,use_ino,func.create=ff,moveonenospc=true,minfreespace=4G,fsname=mergerfs']),
    { shell: false, reject: false }
  )
  if (r.exitCode !== 0) {
    throw new Error(`Failed to mount MergerFS: ${r.stderr}`)
  }
}

// ── fstab persistence ─────────────────────────────────────────────────────────

async function updateFstab(
  mounts: { partition: string; mountPoint: string; role: DiskRole }[],
  poolType: PoolType,
  dataCacheMounts: string[],
): Promise<void> {
  let content = ''
  content = readFileSync('/etc/fstab', 'utf8')

  // Remove previous homenas entries
  content = content
    .split('\n')
    .filter(l => !l.includes('# homenas-v3'))
    .join('\n')
    .trimEnd()

  let additions = '\n\n# HomeNas OS v3 managed entries\n'

  for (const { partition, mountPoint } of mounts) {
    const blkid = await exec('blkid', ['-s', 'UUID', '-o', 'value', partition])
    const uuid = blkid.stdout.trim()
    if (blkid.exitCode !== 0 || !/^[a-fA-F0-9-]+$/.test(uuid)) throw new Error(`Cannot persist UUID for ${partition}`)
    if (uuid) {
      additions += `UUID=${uuid} ${mountPoint} auto defaults,nofail 0 2 # homenas-v3\n`
    }
  }

  if ((poolType === 'mergerfs' || poolType === 'snapraid') && dataCacheMounts.length) {
    // Cache first, then data — matches the ff create policy (first found = cache)
    const sources = dataCacheMounts.join(':')
    additions += `${sources} /mnt/storage fuse.mergerfs defaults,allow_other,use_ino,func.create=ff,moveonenospc=true,minfreespace=4G,fsname=mergerfs,nofail 0 0 # homenas-v3\n`
  }

  if (poolType === 'single' && dataCacheMounts.length === 1) additions += `${dataCacheMounts[0]} /mnt/storage none bind,nofail 0 0 # homenas-v3\n`

  // /etc/fstab is root-owned; the homenas user can't writeFileSync directly.
  await writeRootFile('/etc/fstab', content + additions)
}

// ── Main entry point ──────────────────────────────────────────────────────────

export async function configurePool(config: PoolConfig): Promise<void> {
  return withFormatLock(async () => {
  const { disks, fsType, poolType } = config
  if (!['ext4', 'xfs'].includes(fsType) || !['single', 'mergerfs', 'snapraid'].includes(poolType)) throw new Error('Invalid pool configuration')
  if (disks.some(d => !['data', 'parity', 'cache'].includes(d.role))) throw new Error('Invalid disk role')

  if (disks.length === 0) throw new Error('No disks selected')

  for (const d of disks) validateDevice(d.device)

  await assertSafeToFormat(disks.map(d => d.device))

  const dataDisks   = disks.filter(d => d.role === 'data')
  const parityDisks = disks.filter(d => d.role === 'parity')
  const cacheDisks  = disks.filter(d => d.role === 'cache')

  if (dataDisks.length === 0) throw new Error('At least one data disk required')
  if (poolType === 'single' && (dataDisks.length !== 1 || cacheDisks.length || parityDisks.length)) throw new Error('Single pool requires exactly one data disk')
  if (poolType !== 'snapraid' && parityDisks.length) throw new Error('Parity disks require SnapRAID')
  if (poolType === 'snapraid' && parityDisks.length === 0) {
    throw new Error('SnapRAID requires at least one parity disk')
  }

  let dn = 0, pn = 0, cn = 0
  const targets = disks.map(d => d.role === 'data' ? `/mnt/disks/disk${++dn}` : d.role === 'parity' ? `/mnt/parity${++pn}` : `/mnt/disks/cache${++cn}`)
  for (const target of [...targets, '/mnt/storage']) {
    const mounted = await exec('mountpoint', ['-q', target])
    if (mounted.exitCode === 0) throw new Error(`Mountpoint ${target} is already in use; refusing to format`)
    if (![1, 32].includes(mounted.exitCode)) throw new Error(`Cannot inspect mountpoint ${target}`)
  }

  // 1. Format all disks. Sequential because formatDisk runs `vgchange -an`
  // / `partprobe` / `udevadm settle` which are global to the host — running
  // them concurrently for N disks deactivates LVM mid-format on a sibling and
  // produces flaky failures during install.
  for (const d of disks) {
    await formatDisk(d.device, fsType, d.role)
  }

  // 2. Create mount points and mount
  const mountEntries: { partition: string; mountPoint: string; role: DiskRole }[] = []
  let di = 1, pi = 1, ci = 1

  for (const d of disks) {
    const mp = d.role === 'data'   ? `/mnt/disks/disk${di++}`
             : d.role === 'parity' ? `/mnt/parity${pi++}`
             :                       `/mnt/disks/cache${ci++}`

    // /mnt/disks and /mnt/parity* are root-owned. The backend runs as the
    // homenas user (sudoers NOPASSWD), so mkdirSync would EACCES — use sudo.
    const mkdirResult = await execa(...sudoWrap('mkdir', ['-p', mp]), { shell: false, reject: false })
    if (mkdirResult.exitCode !== 0) throw new Error(`Failed to create mount point ${mp}: ${mkdirResult.stderr}`)

    const partition = partitionDevice(d.device)
    const mountResult = await execa(...sudoWrap('mount', [partition, mp]), { shell: false, reject: false })
    if (mountResult.exitCode !== 0) throw new Error(`Failed to mount ${partition} at ${mp}: ${mountResult.stderr}`)

    if (d.role === 'data' || d.role === 'parity') {
      const snapraidDir = await execa(...sudoWrap('mkdir', ['-p', `${mp}/.snapraid`]), { shell: false, reject: false })
      if (snapraidDir.exitCode !== 0) throw new Error(`Failed to create ${mp}/.snapraid: ${snapraidDir.stderr}`)
    }

    if (d.role !== 'parity') {
      for (const [command, args] of [['groupadd', ['-f', 'sambashare']], ['chown', ['homenas:sambashare', mp]], ['chmod', ['2775', mp]]] as [string, string[]][]) {
        const result = await exec(command, args)
        if (result.exitCode !== 0) throw new Error(`Cannot set disk permissions: ${result.stderr}`)
      }
    }
    mountEntries.push({ partition, mountPoint: mp, role: d.role })
  }

  const dataMounts   = mountEntries.filter(m => m.role === 'data').map(m => m.mountPoint)
  const parityMounts = mountEntries.filter(m => m.role === 'parity').map(m => m.mountPoint)
  const cacheMounts  = mountEntries.filter(m => m.role === 'cache').map(m => m.mountPoint)

  // fstab entry: cache first, then data (matches ff create policy)
  const cacheDataOrdered = [...cacheMounts, ...dataMounts]

  // 3. SnapRAID config (only data + parity, cache is not part of SnapRAID)
  if (poolType === 'snapraid') await writeSnapraidConf(dataMounts, parityMounts)

  // 4. MergerFS pool — cache first so writes land there, drain cron moves to data
  if (poolType === 'mergerfs' || poolType === 'snapraid') {
    await mountMergerFS(cacheMounts.length ? cacheMounts : dataMounts, cacheMounts.length ? dataMounts : [])
  }

  if (poolType === 'single') {
    const created = await exec('mkdir', ['-p', '/mnt/storage'])
    if (created.exitCode !== 0) throw new Error(`Cannot create storage path: ${created.stderr}`)
    const mounted = await exec('mount', ['--bind', dataMounts[0], '/mnt/storage'])
    if (mounted.exitCode !== 0) throw new Error(`Cannot mount single pool: ${mounted.stderr}`)
  }

  // 5. Persist in fstab
  await updateFstab(mountEntries, poolType, cacheDataOrdered)
  })
}
